services:
  bookmark-hub:
    image: bookmark-hub:latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
    network_mode: host
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info
      APP_BIND: "[::]:3000"
      APP_DATA_DIR: /data
      HMAC_KEY: secret
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: main
      PG_PASSWORD: main
      PG_DATABASE: main
      PG_MAX_CONNECTIONS: 5
      OLLAMA_URL: http://localhost:11434
      OLLAMA_TEXT_MODEL: gemma3:4b
      OLLAMA_EMBEDDING_MODEL: nomic-embed-text:v1.5
    volumes:
      - bookmark-hub-data:/data
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      timeout: 2s
      interval: 10s
      start_period: 10s
      retries: 5
    restart: on-failure # needed during startup, until pg is available
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  bookmark-hub-data: