services:
  bookmark-hub:
    image: bookmark-hub:latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - ollama
      - ollama-model-puller
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info
      APP_BIND: "[::]:3000"
      APP_DATA_DIR: /data
      HMAC_KEY: secret
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: main
      PG_PASSWORD: main
      PG_DATABASE: main
      PG_MAX_CONNECTIONS: 5
      OLLAMA_URL: http://ollama:11434
      OLLAMA_TEXT_MODEL: gemma3:4b
    volumes:
      - bookmark-hub-data:/data
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      timeout: 2s
      interval: 10s
      start_period: 10s
      retries: 5
    restart: on-failure # needed during startup, until pg is available
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    volumes:
      - postgres-data:/data/postgres
  ollama:
    image: ollama/ollama:0.9.5
    container_name: ollama
    ports:
      - 11435:11434
    volumes:
      - ollama-data:/root/.ollama
  ollama-model-puller:
    image: curlimages/curl:latest
    command: ["curl", "ollama:11434/api/pull", "-d", "{\"model\":\"gemma3:4b\"}"]
    depends_on:
      - ollama
volumes:
  postgres-data:
  ollama-data:
  bookmark-hub-data:
