services:
  backend:
    build:
      context: backend/
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info,backend=debug
      APP_ENV: DEV
      APP_BIND: "[::]:3000"
      APP_DATA_DIR: /data
      HMAC_KEY: secret
      READABILITY_URL: http://readability-api:3001
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: main
      PG_PASSWORD: main
      PG_DATABASE: main
      PG_MAX_CONNECTIONS: 5
    volumes:
      - backend-data:/data
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      timeout: 2s
      interval: 10s
      start_period: 10s
      retries: 5
    restart: on-failure
  web-spa:
    build:
      context: web-spa/
    depends_on:
      - backend
    ports:
      - 8080:80
    restart: on-failure
  readability-api:
    image: ghcr.io/fparisotto/readability-api:v0.0.1
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    restart: on-failure
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    restart: on-failure
    volumes:
      - postgres-data:/data/postgres
volumes:
  postgres-data:
  backend-data:
