services:
  backend:
    build:
      context: backend/
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
      APP_ENV: DEV
      APP_BIND: "[::]:3000"
      APP_DATA_DIR: /data
      HMAC_KEY: secret
      DB_POOL_SIZE: 5
      DB_URL: postgres://main:main@postgres/main
      READABILITY_URL: http://readability-api:3001
    volumes:
      - backend-data:/data
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      timeout: 2s
      interval: 10s
      start_period: 10s
      retries: 5
  web-spa:
    build:
      context: web-spa/
    depends_on:
      - backend
    ports:
      - 8080:80
  readability-api:
    image: ghcr.io/fparisotto/readability-api:v0.0.1
    environment:
      PORT: 3001
    ports:
      - 3001:3001
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    restart: unless-stopped
    volumes:
      - postgres-data:/data/postgres
volumes:
  postgres-data:
  backend-data:
