[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
  "tailwindcss",
  "-c",
  "tailwind.config.js",
  "-i",
  "styles.css",
  "-o",
  "styles.min.css",
  "--minify",
]

[[proxy]]
rewrite = "/api/v1/"
backend = "http://localhost:3000/api/v1/"

[[proxy]]
rewrite = "/static"
backend = "http://localhost:3000/static"
