[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
  "tailwindcss",
  "-c",
  "tailwind.config.js",
  "-i",
  "styles.css",
  "-o",
  "styles.min.css",
  "--minify",
]
