name: Create and publish a container image in ghcr.io
on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: |
          nix build -L .#default
      - name: Build container image
        run: |
          nix build -L .#containerImage
          echo "container_tag=$(docker load < result | awk '{ print $3 }')" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and push image to ghcr.io
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |-
          nix_tag=${{ env.container_tag }} && hub_tag="$REGISTRY/$REPOSITORY:$IMAGE_TAG" && docker tag "$nix_tag" "$hub_tag" && docker push "$hub_tag"
